/* Support Copilot — frontend.
 *
 * Policy: model-derived content is written with textContent only. HTML-parsing
 * sinks are never used anywhere in this file — the security-scan node enforces
 * that, and a reply body is untrusted text. Nodes are built with
 * createElement/appendChild and cleared with replaceChildren.
 *
 * Backend surface actually available (backend/main.py):
 *   POST /chat            -> { reply }
 *   GET  /api/{table}     -> [row]
 *   POST /api/{table}     -> row (with id)
 * Tables: conversations, messages, knowledge_documents, message_citations,
 * approvals. There is no update/delete endpoint, so derived state (approval
 * status of a conversation) is computed from the approvals table rather than
 * written back onto the conversation row.
 */

/* ---------------------------------------------------------------- constants */

const ANALYST = "Support analyst";
const NO_COVERAGE = "not covered by the product knowledge base";
const DISCLOSURE_PREFIX = "[Automated draft";

/* Fixed by template (disclosure requirement): appended to every approved reply
   and never editable in the draft sheet. */
const DISCLOSURE_LINE =
  "— This reply was drafted by an automated assistant and reviewed by a " +
  "support analyst before sending.";

const DECISIONS = {
  approved: { label: "Approved & sent", tone: "ok" },
  edited_approved: { label: "Edited & approved", tone: "ok" },
  rejected: { label: "Rejected", tone: "dim" },
};

/* ------------------------------------------------------------------- state */

const state = {
  conversationId: null,
  conversationTitle: "",
  turn: 0,
  thread: [], // entries for the active correspondence (client-side view model)
  sending: false,
  recordQuery: "",
};

/* ------------------------------------------------------------------- utils */

function el(tag, className, text) {
  const node = document.createElement(tag);
  if (className) node.className = className;
  if (text !== undefined && text !== null) node.textContent = String(text);
  return node;
}

function clear(node) {
  node.replaceChildren();
}

function $(id) {
  return document.getElementById(id);
}

function clockTime(iso) {
  const d = iso ? new Date(iso) : new Date();
  if (isNaN(d.getTime())) return "";
  return String(d.getHours()).padStart(2, "0") + ":" + String(d.getMinutes()).padStart(2, "0");
}

function shortDate(iso) {
  const d = iso ? new Date(iso) : new Date();
  if (isNaN(d.getTime())) return "";
  const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  return d.getDate() + " " + months[d.getMonth()];
}

function longStamp(iso) {
  const d = iso ? new Date(iso) : new Date();
  if (isNaN(d.getTime())) return "";
  return d.toLocaleString();
}

function titleFrom(question) {
  const flat = question.replace(/\s+/g, " ").trim();
  return flat.length > 72 ? flat.slice(0, 71).trimEnd() + "…" : flat;
}

function showBanner(message) {
  const banner = $("banner");
  banner.textContent = message;
  banner.hidden = false;
}

function hideBanner() {
  const banner = $("banner");
  banner.hidden = true;
  banner.textContent = "";
}

/* --------------------------------------------------------------------- api */

async function request(path, options) {
  const response = await fetch(path, options);
  if (!response.ok) {
    throw new Error("Request to " + path + " failed (" + response.status + ")");
  }
  return response.json();
}

function listRows(table) {
  return request("/api/" + table);
}

function insertRow(table, row) {
  return request("/api/" + table, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(row),
  });
}

function askAgent(message) {
  return request("/chat", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ message: message }),
  });
}

/* ------------------------------------------------------------ reply parsing */

/* The runtime returns a plain-text draft shaped as blank-line separated blocks:
 *   [Automated draft - generated by <agent>; pending analyst approval]
 *   <body paragraphs…>
 *   Sources: <doc-id> (<title>)          <- one line per cited document
 * Anything unrecognised is preserved verbatim as body text; we never drop
 * content we failed to classify. */
function parseReply(raw) {
  const blocks = String(raw == null ? "" : raw)
    .split(/\n\s*\n/)
    .map((block) => block.trim())
    .filter(Boolean);

  let agent = "";
  if (blocks.length && blocks[0].startsWith(DISCLOSURE_PREFIX)) {
    const disclosure = blocks.shift();
    const match = disclosure.match(/generated by\s+([^;\]]+)/);
    agent = match ? match[1].trim() : "";
  }

  const sources = [];
  const body = [];
  blocks.forEach((block) => {
    const lines = block.split("\n").map((line) => line.trim()).filter(Boolean);
    const isSourceBlock = lines.length > 0 && lines.every((line) => /^Sources:/i.test(line));
    if (isSourceBlock) {
      lines.forEach((line) => {
        const match = line.match(/^Sources:\s*(.+?)\s*\((.+)\)\s*$/i);
        if (match) {
          sources.push({ id: match[1], title: match[2] });
        } else {
          sources.push({ id: line.replace(/^Sources:\s*/i, ""), title: "" });
        }
      });
    } else {
      body.push(block);
    }
  });

  const covered = !String(raw == null ? "" : raw).includes(NO_COVERAGE) && sources.length > 0;
  return {
    agent: agent,
    paragraphs: body,
    sources: sources,
    covered: covered,
    bodyText: body.join("\n\n"),
  };
}

/* --------------------------------------------------------- assist rendering */

function renderThread() {
  const thread = $("thread");
  clear(thread);
  $("thread-empty").hidden = state.thread.length > 0;

  state.thread.forEach((entry) => {
    const li = el("li", "entry" + (entry.pending ? " thinking" : ""));

    const attrib = el("div", "attrib");
    attrib.appendChild(el("b", null, entry.who));
    attrib.appendChild(document.createTextNode(" · " + entry.time));
    (entry.stamps || []).forEach((stamp) => {
      attrib.appendChild(document.createTextNode(" · "));
      attrib.appendChild(el("span", "stamp " + (stamp.tone || ""), stamp.label));
    });
    li.appendChild(attrib);

    entry.paragraphs.forEach((text, index) => {
      const useDrop = index === 0 && entry.drop && text.length > 40;
      li.appendChild(el("p", useDrop ? "drop" : null, text));
    });

    if (entry.sources && entry.sources.length) {
      const line = el("div", "srcline");
      line.appendChild(document.createTextNode("Sources: "));
      entry.sources.forEach((source, index) => {
        if (index > 0) line.appendChild(document.createTextNode(" · "));
        line.appendChild(el("sup", null, String(index + 1)));
        line.appendChild(el("span", null, source.title || source.id));
      });
      li.appendChild(line);
    }

    thread.appendChild(li);
  });
}

function renderSourcesMargin() {
  const margin = $("sources-margin");
  clear(margin);

  const latest = [...state.thread].reverse().find((entry) => entry.sources && entry.sources.length);
  if (!latest) {
    margin.appendChild(
      el("div", "fnote", "No sources cited yet. They appear here as the assistant answers.")
    );
    return;
  }

  latest.sources.forEach((source, index) => {
    const note = el("div", "fnote");
    note.appendChild(el("b", null, index + 1 + "."));
    note.appendChild(document.createTextNode(" "));
    note.appendChild(el("span", null, source.title || source.id));
    if (source.title && source.id) {
      const id = el("i", null, " " + source.id);
      note.appendChild(id);
    }
    margin.appendChild(note);
  });
}

function renderAssistHeader() {
  $("assist-title").textContent = state.conversationTitle || "New correspondence";
  const sub = state.conversationId
    ? "A correspondence between the analyst and the assistant. Record #" + state.conversationId + "."
    : "A correspondence between the analyst and the assistant.";
  $("assist-sub").textContent = sub;
}

/* ------------------------------------------------------------- assist: send */

async function send(question) {
  const now = new Date().toISOString();
  state.thread.push({
    who: "Analyst",
    time: clockTime(now),
    paragraphs: [question],
  });
  const placeholder = {
    who: "Assistant",
    time: clockTime(now),
    paragraphs: ["Searching the ingested knowledge…"],
    pending: true,
  };
  state.thread.push(placeholder);
  renderThread();
  renderSourcesMargin();

  try {
    if (!state.conversationId) {
      const conversation = await insertRow("conversations", {
        title: titleFrom(question),
        customer_question: question,
        analyst: ANALYST,
        approval_status: "awaiting_approval",
        created_at: now,
        updated_at: now,
      });
      state.conversationId = conversation.id;
      state.conversationTitle = conversation.title;
      renderAssistHeader();
    }

    await insertRow("messages", {
      conversation_id: state.conversationId,
      role: "analyst",
      content: question,
      turn_index: state.turn++,
      is_draft_reply: false,
      is_automated: false,
      coverage_status: "not_applicable",
      created_at: now,
    });

    const data = await askAgent(question);
    const parsed = parseReply(data.reply);
    const repliedAt = new Date().toISOString();

    const draft = await insertRow("messages", {
      conversation_id: state.conversationId,
      role: "assistant",
      content: parsed.bodyText,
      turn_index: state.turn++,
      is_draft_reply: true,
      is_automated: true,
      coverage_status: parsed.covered ? "grounded" : "no_covering_source",
      created_at: repliedAt,
    });

    for (const source of parsed.sources) {
      await insertRow("message_citations", {
        message_id: draft.id,
        document_id: source.id,
        document_title: source.title,
        locator: "",
        excerpt: "",
      });
    }

    const stamps = [{ label: "Automated draft", tone: "" }];
    if (!parsed.covered) stamps.push({ label: "Outside the corpus", tone: "warn" });

    Object.assign(placeholder, {
      time: clockTime(repliedAt),
      paragraphs: parsed.paragraphs.length ? parsed.paragraphs : ["(empty reply)"],
      sources: parsed.sources,
      stamps: stamps,
      pending: false,
      drop: parsed.covered,
    });

    hideBanner();
  } catch (err) {
    Object.assign(placeholder, {
      paragraphs: ["The request failed, so there is no draft for this turn."],
      stamps: [{ label: "Failed", tone: "bad" }],
      pending: false,
    });
    showBanner(err.message);
  }

  renderThread();
  renderSourcesMargin();
  refreshAll();
}

/* ------------------------------------------------------ approvals rendering */

function decisionOf(approvals, messageId) {
  const matches = approvals.filter((row) => row.message_id === messageId);
  return matches.length ? matches[matches.length - 1] : null;
}

function renderApprovals(data) {
  const list = $("approval-list");
  clear(list);

  const decided = new Set(data.approvals.map((row) => row.message_id));
  const pending = data.messages.filter((row) => row.is_draft_reply && !decided.has(row.id));

  $("pending-count").textContent = pending.length ? "·" + pending.length : "";
  $("approvals-sub").textContent = pending.length
    ? pending.length + " draft(s) await a decision. Nothing leaves this desk unapproved."
    : "Nothing awaiting a decision. Nothing leaves this desk unapproved.";

  if (!pending.length) {
    list.appendChild(
      el("p", "empty", "No drafts are waiting. Ask a question on the Assist screen to produce one.")
    );
    return;
  }

  pending.forEach((message) => {
    const conversation = data.conversations.find((row) => row.id === message.conversation_id);
    const citations = data.citations.filter((row) => row.message_id === message.id);
    const uncovered = message.coverage_status === "no_covering_source";

    const sheet = el("div", "sheet");

    const head = el("div", "head");
    const heading = el("div");
    heading.appendChild(el("b", null, "#" + message.conversation_id));
    heading.appendChild(document.createTextNode(" "));
    heading.appendChild(el("span", "meta", "— " + (conversation ? conversation.title : "untitled")));
    head.appendChild(heading);
    head.appendChild(
      el("span", "stamp " + (uncovered ? "warn" : ""), uncovered ? "No covering source" : "Awaiting approval")
    );
    sheet.appendChild(head);

    const textarea = el("textarea");
    textarea.value = message.content;
    sheet.appendChild(textarea);

    sheet.appendChild(el("p", "fixed-line", DISCLOSURE_LINE));

    if (citations.length) {
      const cited = el("ul", "cited");
      citations.forEach((row, index) => {
        const item = el("li");
        item.appendChild(el("b", null, index + 1 + "."));
        item.appendChild(document.createTextNode(" " + (row.document_title || row.document_id)));
        cited.appendChild(item);
      });
      sheet.appendChild(cited);
    } else {
      sheet.appendChild(
        el("p", "ledger", "No sources were cited for this draft — verify it independently before approving.")
      );
    }

    const actions = el("div", "actions");
    const approve = el("button", "btn-p", "Approve & send");
    const editApprove = el("button", "btn-s", "Save edit, then approve");
    const reject = el("button", "btn-d", "Reject");
    actions.appendChild(approve);
    actions.appendChild(editApprove);
    actions.appendChild(reject);
    sheet.appendChild(actions);

    const status = el(
      "div",
      "ledger",
      "No decision recorded yet. On approval the record keeps: approver, decision, " +
        "timestamp, and whether you edited the text."
    );
    sheet.appendChild(status);

    const decide = async (decision) => {
      [approve, editApprove, reject].forEach((button) => {
        button.disabled = true;
      });
      const wasEdited = textarea.value.trim() !== String(message.content).trim();
      try {
        await insertRow("approvals", {
          conversation_id: message.conversation_id,
          message_id: message.id,
          decision: decision,
          approver: ANALYST,
          was_edited: wasEdited,
          drafted_text: message.content,
          final_text:
            decision === "rejected" ? "" : textarea.value.trim() + "\n\n" + DISCLOSURE_LINE,
          note: "",
          decided_at: new Date().toISOString(),
        });
        hideBanner();
        refreshAll();
      } catch (err) {
        [approve, editApprove, reject].forEach((button) => {
          button.disabled = false;
        });
        showBanner(err.message);
      }
    };

    approve.addEventListener("click", () => decide("approved"));
    editApprove.addEventListener("click", () => decide("edited_approved"));
    reject.addEventListener("click", () => decide("rejected"));

    list.appendChild(sheet);
  });
}

/* --------------------------------------------------------- record rendering */

function renderRecord(data) {
  const list = $("record-list");
  clear(list);

  const query = state.recordQuery.trim().toLowerCase();
  const rows = data.conversations
    .slice()
    .reverse()
    .filter((conversation) => {
      if (!query) return true;
      const haystack = [conversation.title, conversation.customer_question]
        .filter(Boolean)
        .join(" ")
        .toLowerCase();
      return haystack.includes(query);
    });

  if (!rows.length) {
    list.appendChild(
      el(
        "p",
        "empty",
        data.conversations.length
          ? "Nothing in the record matches that search."
          : "The record is empty. Answered questions are kept here for review and reuse."
      )
    );
    return;
  }

  rows.forEach((conversation) => {
    const drafts = data.messages.filter(
      (row) => row.conversation_id === conversation.id && row.is_draft_reply
    );
    const citationCount = drafts.reduce(
      (total, draft) => total + data.citations.filter((row) => row.message_id === draft.id).length,
      0
    );
    const decisions = drafts
      .map((draft) => decisionOf(data.approvals, draft.id))
      .filter(Boolean);
    const latest = decisions.length ? decisions[decisions.length - 1] : null;
    const awaiting = drafts.length > decisions.length;

    const rec = el("div", "rec");
    rec.appendChild(el("div", "date", shortDate(conversation.created_at)));

    const middle = el("div");
    middle.appendChild(el("h3", null, conversation.title || "Untitled"));
    const detail =
      "#" + conversation.id + " · " + conversation.analyst + " · " +
      (citationCount === 1 ? "1 source cited" : citationCount + " sources cited");
    middle.appendChild(el("p", null, detail));
    rec.appendChild(middle);

    const end = el("div", "end");
    if (awaiting) {
      end.appendChild(el("span", "stamp warn", "Awaiting"));
      const open = el("button", "btn-s", "Open");
      open.addEventListener("click", () => showScreen("approvals"));
      end.appendChild(open);
    } else if (latest) {
      const meta = DECISIONS[latest.decision] || { label: latest.decision, tone: "dim" };
      end.appendChild(el("span", "stamp " + meta.tone, meta.label));
      if (latest.final_text) {
        const reuse = el("button", "btn-s", "Reuse");
        reuse.addEventListener("click", () => {
          $("input").value = latest.final_text;
          showScreen("assist");
          $("input").focus();
          $("record-note").textContent =
            "Copied — the approved wording is now in the composer as a starting point.";
        });
        end.appendChild(reuse);
      }
    } else {
      end.appendChild(el("span", "stamp dim", "No draft"));
    }
    rec.appendChild(end);

    if (latest) {
      const ledger = el(
        "div",
        "ledger",
        "Recorded — " +
          (DECISIONS[latest.decision] || { label: latest.decision }).label +
          " by " + latest.approver +
          " on " + longStamp(latest.decided_at) +
          ". Edited: " + (latest.was_edited ? "yes" : "no") + "."
      );
      ledger.style.gridColumn = "2 / -1";
      rec.appendChild(ledger);
    }

    list.appendChild(rec);
  });
}

/* ------------------------------------------------------ knowledge rendering */

function renderKnowledge(data) {
  const list = $("knowledge-list");
  clear(list);

  /* Two real sources of truth: documents registered in the table, and documents
     the assistant actually cited. Neither is invented here. */
  const docs = new Map();
  data.documents.forEach((doc) => {
    docs.set(doc.source_path || doc.title, {
      title: doc.title,
      meta: doc.ingested_at ? "ingested " + longStamp(doc.ingested_at) : "",
      excerpt: doc.content || "",
      cites: 0,
    });
  });
  data.citations.forEach((row) => {
    const key = row.document_id || row.document_title;
    if (!key) return;
    if (!docs.has(key)) {
      docs.set(key, { title: row.document_title || key, meta: key, excerpt: "", cites: 0 });
    }
    docs.get(key).cites += 1;
  });

  const entries = [...docs.values()].sort((a, b) => b.cites - a.cites);

  $("knowledge-sub").textContent = entries.length
    ? "Everything the assistant is allowed to know — " + entries.length + " document(s) seen so far."
    : "Everything the assistant is allowed to know.";

  if (!entries.length) {
    list.appendChild(
      el(
        "p",
        "empty",
        "No documents have been cited yet. The corpus is loaded server-side at ingest " +
          "time; documents appear here once the assistant draws on them."
      )
    );
  }

  entries.forEach((entry) => {
    const card = el("div", "card");
    card.appendChild(el("h3", null, entry.title));
    const bits = [entry.meta, entry.cites === 1 ? "cited by 1 answer" : "cited by " + entry.cites + " answers"];
    card.appendChild(el("div", "meta", bits.filter(Boolean).join(" · ")));
    if (entry.excerpt) card.appendChild(el("blockquote", null, entry.excerpt));
    list.appendChild(card);
  });

  const gaps = data.messages.filter((row) => row.coverage_status === "no_covering_source").length;
  $("gaps-note").textContent = gaps
    ? gaps + " question(s) had no covering passage. The assistant deferred each time rather than answer."
    : "No question so far has fallen outside the corpus. When one does, the assistant defers instead of guessing.";
}

/* ------------------------------------------------------------- refresh loop */

async function refreshAll() {
  try {
    const [conversations, messages, approvals, citations, documents] = await Promise.all([
      listRows("conversations"),
      listRows("messages"),
      listRows("approvals"),
      listRows("message_citations"),
      listRows("knowledge_documents"),
    ]);
    const data = {
      conversations: conversations,
      messages: messages,
      approvals: approvals,
      citations: citations,
      documents: documents,
    };
    renderApprovals(data);
    renderRecord(data);
    renderKnowledge(data);
  } catch (err) {
    showBanner("Could not load stored records: " + err.message);
  }
}

/* -------------------------------------------------------------- navigation */

function showScreen(id) {
  document.querySelectorAll(".screen").forEach((section) => {
    section.classList.toggle("active", section.id === id);
  });
  document.querySelectorAll("#nav a").forEach((link) => {
    link.classList.toggle("is-on", link.dataset.screen === id);
  });
  window.scrollTo(0, 0);
}

/* ------------------------------------------------------------------- wiring */

$("nav").addEventListener("click", (event) => {
  const link = event.target.closest("[data-screen]");
  if (!link) return;
  event.preventDefault();
  showScreen(link.dataset.screen);
});

$("composer").addEventListener("submit", async (event) => {
  event.preventDefault();
  if (state.sending) return;
  const input = $("input");
  const question = input.value.trim();
  if (!question) return;

  state.sending = true;
  $("ask").disabled = true;
  input.value = "";
  try {
    await send(question);
  } finally {
    state.sending = false;
    $("ask").disabled = false;
    input.focus();
  }
});

$("input").addEventListener("keydown", (event) => {
  if (event.key === "Enter" && !event.shiftKey) {
    event.preventDefault();
    $("composer").requestSubmit();
  }
});

$("record-search").addEventListener("input", (event) => {
  state.recordQuery = event.target.value;
  refreshAll();
});

renderAssistHeader();
renderThread();
renderSourcesMargin();
refreshAll();
