"""Support Copilot — generated by the harness agentic-app scaffold.

Composition contract: db (persistence-core), agent_runtime (agent-runtime),
models.TABLES (generated from the approved data model).
"""
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

from agent_runtime import respond
from db import store
from models import TABLES

app = FastAPI(title="Support Copilot")


class ChatRequest(BaseModel):
    message: str


@app.get("/health")
def health():
    return {"status": "ok"}


@app.post("/chat")
def chat(req: ChatRequest):
    return {"reply": respond(req.message)}


@app.get("/api/{table}")
def list_rows(table: str):
    if table not in TABLES:
        raise HTTPException(status_code=404, detail="unknown table")
    return store.list(table)


@app.post("/api/{table}")
def create_row(table: str, row: dict):
    if table not in TABLES:
        raise HTTPException(status_code=404, detail="unknown table")
    return store.insert(table, row)


class ApprovalRequest(BaseModel):
    message: str


@app.post("/approvals")
def approve(req: ApprovalRequest):
    row = store.insert("approvals", {"message": req.message, "approved": True})
    return {"approved": True, "id": row["id"]}
