server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /chat {
        proxy_pass http://backend:8000/chat;
    }
    location /api/ {
        proxy_pass http://backend:8000/api/;
    }
}
