"""__APP_NAME__ — generated by the harness agentic-app scaffold.

Composition contract: db (persistence-core), agent_runtime (agent-runtime),
models.TABLES (generated from the approved data model).
"""
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

from agent_runtime import mode, respond
from db import store
from models import TABLES

app = FastAPI(title="__APP_NAME__")


class ChatRequest(BaseModel):
    message: str


@app.get("/health")
def health():
    return {"status": "ok"}


@app.get("/agent/mode")
def agent_mode():
    return mode()


@app.post("/chat")
def chat(req: ChatRequest):
    return {"reply": respond(req.message)}


@app.get("/api/{table}")
def list_rows(table: str):
    if table not in TABLES:
        raise HTTPException(status_code=404, detail="unknown table")
    return store.list(table)


@app.post("/api/{table}")
def create_row(table: str, row: dict):
    if table not in TABLES:
        raise HTTPException(status_code=404, detail="unknown table")
    return store.insert(table, row)
