"""__APP_NAME__ — generated by the harness agentic-app scaffold.

Composition contract: db (persistence-core), agent_runtime (agent-runtime),
models.TABLES (generated from the approved data model).
"""
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

from agent_runtime import mode, respond
from db import store
from models import OPEN_READ_TABLES, OPEN_WRITE_TABLES, TABLES

app = FastAPI(title="__APP_NAME__")

# Composed module extensions: any backend/ext_*.py exposing `router` mounts
# automatically. This is how capability modules add API surface without ever
# editing this file — the module system's extension point.
import glob as _glob  # noqa: E402
import importlib as _importlib  # noqa: E402
import os as _os  # noqa: E402

for _ext in sorted(_glob.glob(_os.path.join(_os.path.dirname(__file__), "ext_*.py"))):
    _mod = _importlib.import_module(_os.path.basename(_ext)[:-3])
    if hasattr(_mod, "router"):
        app.include_router(_mod.router)
    if hasattr(_mod, "install"):
        _mod.install(app)


class ChatRequest(BaseModel):
    message: str


@app.get("/health")
def health():
    return {"status": "ok"}


@app.get("/agent/mode")
def agent_mode():
    return mode()


@app.get("/agents")
def agents():
    """The app's configured agent roster — roles, tools, guardrails, evals.

    Transparency contract: users can always see which agents an app runs.
    """
    import json
    import os

    roster_path = os.path.join(os.path.dirname(__file__), "..", "agents", "roster.json")
    with open(roster_path, encoding="utf-8") as f:
        return json.load(f)


@app.post("/chat")  # public-endpoint: the app's front-door conversational surface
def chat(req: ChatRequest):
    return {"reply": respond(req.message)}


# Generic table API — DEFAULT CLOSED. Only tables the approved data model
# explicitly exposes (access: "open"/"read") are served here; everything else
# must go through explicit endpoints that carry identity and role checks.
@app.get("/api/{table}")  # public-endpoint: reads limited to the model's open allowlist
def list_rows(table: str):
    if table not in TABLES:
        raise HTTPException(status_code=404, detail="unknown table")
    if table not in OPEN_READ_TABLES:
        raise HTTPException(status_code=403, detail=f"table '{table}' is not exposed via the generic API — use its explicit endpoints")
    return store.list(table)


@app.post("/api/{table}")  # public-endpoint: writes limited to the model's open allowlist
def create_row(table: str, row: dict):
    if table not in TABLES:
        raise HTTPException(status_code=404, detail="unknown table")
    if table not in OPEN_WRITE_TABLES:
        raise HTTPException(status_code=403, detail=f"table '{table}' does not accept generic writes — use its explicit endpoints")
    return store.insert(table, row)
