"""Support Copilot — generated by the harness agentic-app scaffold.

Composition contract: db (persistence-core), agent_runtime (agent-runtime),
models.TABLES (generated from the approved data model).
"""
import uuid
from datetime import datetime, timezone

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

from agent_runtime import corpus_info, mode, respond_with_citations
from db import store
from models import TABLES

app = FastAPI(title="Support Copilot")


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


class ChatRequest(BaseModel):
    message: str
    conversation_id: str | None = None


class ApprovalRequest(BaseModel):
    conversation_id: str
    decision: str  # "approve" | "reject"
    analyst_id: str
    edited_draft: str | None = None


@app.get("/health")
def health():
    return {"status": "ok"}


@app.get("/agent/mode")
def agent_mode():
    return mode()


@app.get("/agents")
def agents():
    """The app's configured agent roster — roles, tools, guardrails, evals.

    Transparency contract: users can always see which agents an app runs.
    """
    import json
    import os

    roster_path = os.path.join(os.path.dirname(__file__), "..", "agents", "roster.json")
    with open(roster_path, encoding="utf-8") as f:
        return json.load(f)


@app.get("/corpus")
def corpus():
    """The product-knowledge corpus loaded from the local documents folder at
    startup (REQ-017) — visible so an analyst can see what the assistant is
    grounded in before trusting a draft."""
    return corpus_info()


def _find_conversation(conversation_id: str) -> dict | None:
    for row in store.list("conversations"):
        if row.get("conversation_id") == conversation_id:
            return row
    return None


def _ensure_conversation(conversation_id: str, subject: str) -> dict:
    """A client-supplied conversation_id is stable: reuse the row if it already exists."""
    existing = _find_conversation(conversation_id)
    if existing:
        return existing
    now = _now()
    return store.insert(
        "conversations",
        {"conversation_id": conversation_id, "created_at": now, "updated_at": now, "subject": subject[:120]},
    )


def _messages_for_conversation(conversation_id: str) -> list:
    return [m for m in store.list("messages") if m.get("conversation_id") == conversation_id]


def _latest_message_for_conversation(conversation_id: str) -> dict | None:
    """The draft under review is always the most recent turn in the thread —
    approvals decide on that draft (REQ-009/REQ-012)."""
    msgs = _messages_for_conversation(conversation_id)
    return msgs[-1] if msgs else None


def _find_message(message_id) -> dict | None:
    for row in store.list("messages"):
        if row.get("id") == message_id:
            return row
    return None


def _latest_approval_for_conversation(conversation_id: str) -> dict | None:
    """The most recent analyst decision recorded for this conversation's
    draft — a later re-approval/rejection supersedes an earlier one."""
    approvals = [a for a in store.list("approvals") if a.get("conversation_id") == conversation_id]
    return approvals[-1] if approvals else None


@app.post("/chat")
def chat(req: ChatRequest):
    # conversation_id is optional (REQ-002): a bare {"message": ...} still works
    # and still returns "reply" — the base test suite and compose smoke keep passing.
    conversation_id = req.conversation_id or f"conv-{uuid.uuid4().hex[:12]}"
    _ensure_conversation(conversation_id, req.message)
    sequence = sum(1 for m in store.list("messages") if m.get("conversation_id") == conversation_id) + 1

    # Retrieval before generation (REQ-003): the reply is composed only from
    # what the corpus search found, and the same search backs the citations
    # shown to the analyst and filed with the conversation record (REQ-011).
    reply, sources = respond_with_citations(req.message)

    message = store.insert(
        "messages",
        {
            "conversation_id": conversation_id,
            "sequence": sequence,
            "role": "assistant",
            "analyst_question": req.message,
            "assistant_draft": reply,
            "created_at": _now(),
        },
    )
    citations = [
        store.insert(
            "citations",
            {
                "message_id": message["id"],
                "source_title": source["title"],
                "source_passage": source["passage"],
                "source_url": source.get("url", ""),
            },
        )
        for source in sources
    ]
    return {"reply": reply, "conversation_id": conversation_id, "message_id": message["id"], "citations": citations}


@app.post("/approvals")
def create_approval(req: ApprovalRequest):
    """The analyst approval gate (REQ-009, REQ-012, REQ-013, REQ-018): an
    analyst approves the draft as-is, edits it and then approves, or rejects
    it. Registered outside /api/ so it is never shadowed by the /api/{table}
    catch-all below. Every decision records who decided, when, and whether
    the draft text was edited — nothing here ever sends or delivers
    anything; that stays a manual analyst action outside this app."""
    conversation = _find_conversation(req.conversation_id)
    if not conversation:
        raise HTTPException(status_code=404, detail="unknown conversation")
    message = _latest_message_for_conversation(req.conversation_id)
    if not message:
        raise HTTPException(status_code=404, detail="conversation has no draft awaiting a decision yet")
    if req.decision not in ("approve", "reject"):
        raise HTTPException(status_code=400, detail="decision must be 'approve' or 'reject'")
    return store.insert(
        "approvals",
        {
            "conversation_id": req.conversation_id,
            "message_id": message["id"],
            "decision": req.decision,
            "analyst_id": req.analyst_id,
            "edited_draft": req.edited_draft,
            "was_edited": bool(req.edited_draft),
            "approved_at": _now(),
        },
    )


@app.get("/conversations/{conversation_id}/approved-reply")
def approved_reply(conversation_id: str):
    """The approved text only becomes available here after an analyst
    approves it (REQ-009, REQ-013) — an unapproved or rejected draft can
    never leave the application through this endpoint."""
    conversation = _find_conversation(conversation_id)
    if not conversation:
        raise HTTPException(status_code=404, detail="unknown conversation")
    approval = _latest_approval_for_conversation(conversation_id)
    if not approval or approval.get("decision") != "approve":
        raise HTTPException(status_code=409, detail="not approved: this conversation has no approved draft yet")
    message = _find_message(approval.get("message_id"))
    original_draft = message.get("assistant_draft", "") if message else ""
    reply = approval.get("edited_draft") or original_draft
    return {
        "conversation_id": conversation_id,
        "message_id": approval.get("message_id"),
        "reply": reply,
        "original_draft": original_draft,
        "analyst_id": approval.get("analyst_id"),
        "decision": approval.get("decision"),
        "was_edited": approval.get("was_edited"),
        "approved_at": approval.get("approved_at"),
    }


@app.get("/conversations")
def list_conversations():
    """Every conversation ever started, most recent first (REQ-004): records
    persist beyond the active session — nothing here is purged automatically,
    they last until someone deletes them by hand (REQ-014)."""
    return sorted(store.list("conversations"), key=lambda c: c.get("created_at", ""), reverse=True)


@app.get("/conversations/{conversation_id}")
def conversation_detail(conversation_id: str):
    """The full record for one conversation (REQ-005): every turn's analyst
    question, the assistant's draft, the citations behind that draft, and the
    most recent approval decision — who decided, when, and whether the draft
    was edited — everything a later quality review needs (REQ-016 keeps this
    a single flat lookup; no per-analyst scoping is implemented, per
    REQ-019)."""
    conversation = _find_conversation(conversation_id)
    if not conversation:
        raise HTTPException(status_code=404, detail="unknown conversation")
    all_citations = store.list("citations")
    messages_out = [
        {
            **message,
            "citations": [c for c in all_citations if c.get("message_id") == message["id"]],
        }
        for message in _messages_for_conversation(conversation_id)
    ]
    approval = _latest_approval_for_conversation(conversation_id)
    return {**conversation, "messages": messages_out, "approval": approval}


@app.get("/api/{table}")
def list_rows(table: str):
    if table not in TABLES:
        raise HTTPException(status_code=404, detail="unknown table")
    return store.list(table)


@app.post("/api/{table}")
def create_row(table: str, row: dict):
    if table not in TABLES:
        raise HTTPException(status_code=404, detail="unknown table")
    return store.insert(table, row)
