"""agent-runtime module: deterministic runtime for the approved agent roster.

`respond()` is the single entry point the rest of the app may call. It routes a
message to one of the rostered agents and returns the DRAFT reply text.

Roster contract honoured here (agents/roster.json):
  * every reply opens with the disclosure prefix
    "[Automated draft - generated by {agent_name}; pending analyst approval]"
  * answers are grounded in the ingested corpus (agents/corpus_index.json);
    only doc_ids present in that index may be cited
  * when the corpus does not answer the question the agent says
    "not covered by the product knowledge base" and hands off to an analyst
  * no agent has a send/deliver tool - approval is an analyst action
  * precedent lookups are filtered to approved records inside the 90-day
    retention window and are never bulk-dumped

The behaviour is rule-based and deterministic so `agents/run_evals.py` is a
reproducible gate. A model-backed implementation may replace the bodies of the
`_respond_*` functions as long as this module keeps the same public surface
(`respond`, `AGENT_NAMES`, `DEFAULT_AGENT`) and the evals stay green.
"""
import datetime
import json
import os
import re

BASE = os.path.dirname(os.path.abspath(__file__))
AGENTS_DIR = os.path.join(BASE, "..", "agents")

DEFAULT_AGENT = "support_draft_agent"
AGENT_NAMES = ("support_draft_agent", "precedent_finder")

NO_COVERAGE_PHRASE = "not covered by the product knowledge base"
RETENTION_DAYS = 90
MAX_PRECEDENT_RESULTS = 5

_STOPWORDS = {
    "a", "about", "an", "and", "answer", "any", "are", "as", "at", "be", "by",
    "can", "customer", "customers", "do", "does", "every", "find", "for",
    "from", "get", "give", "has", "have", "help", "how", "i", "in", "is", "it",
    "its", "know", "last", "me", "my", "need", "of", "on", "one", "or", "our",
    "past", "please", "previous", "prior", "question", "show", "some", "tell",
    "that", "the", "their", "them", "there", "they", "this", "to", "up", "us",
    "was", "we", "what", "when", "where", "which", "who", "why", "will",
    "with", "you", "your",
}


def _load(name):
    with open(os.path.join(AGENTS_DIR, name)) as handle:
        return json.load(handle)


def _roster():
    return _load("roster.json")


def _corpus():
    return _load("corpus_index.json")["documents"]


def _conversations():
    return _load("precedent_index.json")


def _disclosure(agent_name):
    return "[Automated draft - generated by %s; pending analyst approval]" % agent_name


def _tokens(message):
    words = re.findall(r"[a-z0-9][a-z0-9'-]*", message.lower())
    return {w for w in words if w not in _STOPWORDS}


def _mentions(message, phrases):
    """Whole-word phrase match, so 'ever' never fires on 'every'."""
    low = message.lower()
    return any(
        re.search(r"\b%s\b" % re.escape(phrase), low) for phrase in phrases
    )


def _search(message, records):
    """Keyword retrieval: a record matches only on an explicit keyword hit."""
    tokens = _tokens(message)
    hits = []
    for record in records:
        overlap = tokens & {k.lower() for k in record.get("keywords", [])}
        if overlap:
            hits.append((len(overlap), record))
    hits.sort(key=lambda pair: (-pair[0], pair[1].get("doc_id") or pair[1].get("conversation_id")))
    return [record for _score, record in hits]


# --------------------------------------------------------------------------
# support_draft_agent
# --------------------------------------------------------------------------

_OFF_DOMAIN = (
    "poem", "poetry", "sonnet", "haiku", "limerick", "song", "lyrics", "joke",
    "short story", "write me a story", "recipe", "screenplay", "rap",
)
_DELIVERY = (
    "send that", "send this", "send it", "send the answer", "send the reply",
    "email that", "email this", "email it", "deliver it", "send to the customer",
    "send that answer", "reply to the customer for me",
)
_UNGROUNDED = (
    "ignore the documents", "ignore the document", "ignore the docs",
    "ignore your documents", "your own general knowledge",
    "your general knowledge", "from memory", "without the documents",
    "forget the corpus", "ignore the corpus",
)
_GREETING = ("hi", "hello", "hey", "good morning", "good afternoon")


def _citation_lines(docs):
    return [
        "Sources: %s (%s)" % (doc["doc_id"], doc["title"])
        for doc in docs
    ]


def _respond_support_draft(message):
    prefix = _disclosure("support_draft_agent")
    low = message.strip().lower()

    if _mentions(message, _DELIVERY):
        return "\n\n".join([
            prefix,
            "I have no delivery tool and no outbound channel, so nothing leaves this "
            "workspace on my account. This text stays a draft until a support analyst "
            "approves it; on approval the app records the decision and the analyst "
            "copies the approved text into the existing email tool.",
        ])

    if _mentions(message, _OFF_DOMAIN):
        return "\n\n".join([
            prefix,
            "That request is outside my scope, so I cannot help with it. I only draft "
            "product support answers grounded in the ingested knowledge base; ask me a "
            "product or support question and I will search the corpus and cite what I used.",
        ])

    preamble = []
    if _mentions(message, _UNGROUNDED):
        preamble.append(
            "I answer only from the ingested product knowledge base, never from my own "
            "general memory, so I will keep this grounded in the ingested documents."
        )

    docs = _search(message, _corpus())

    first_word = re.findall(r"[a-z]+", low)[:1]
    is_greeting = bool(first_word) and first_word[0] in _GREETING

    if not docs:
        if is_greeting and not preamble:
            return "\n\n".join([
                prefix,
                "Yes. Ask the product question and I will search the ingested product "
                "knowledge base, draft an answer for your review, and cite the knowledge "
                "sources I used.",
            ])
        return "\n\n".join([
            prefix,
        ] + preamble + [
            "I searched the ingested product knowledge base and found no grounded "
            "answer: this question is %s." % NO_COVERAGE_PHRASE,
            "Next step: escalate to a human support analyst who can research it and "
            "confirm the answer. I will not fill the gap with an unsupported claim.",
        ])

    cited = docs[:2]
    body = " ".join(doc["text"] for doc in cited)
    return "\n\n".join([
        prefix,
    ] + preamble + [
        body,
        "\n".join(_citation_lines(cited)),
    ])


# --------------------------------------------------------------------------
# precedent_finder
# --------------------------------------------------------------------------

_BEYOND_WINDOW = (
    "year", "years", "all time", "all-time", "since the beginning", "ever",
    "entire history", "whole history", "archive",
)
_BULK = (
    "dump", "every stored", "all stored", "everything you have",
    "all conversations", "every conversation you", "all of the conversations",
    "list them all", "export everything",
)


def _within_retention(record, today):
    created = datetime.date.fromisoformat(record["created_at"])
    return 0 <= (today - created).days <= RETENTION_DAYS


def _respond_precedent_finder(message):
    prefix = _disclosure("precedent_finder")

    if _mentions(message, _BEYOND_WINDOW):
        return "\n\n".join([
            prefix,
            "I cannot cover that span. Stored conversations follow a 90-day retention "
            "policy: records older than 90 days are purged and are not searchable, so I "
            "only search approved conversations inside the trailing 90-day window.",
            "Narrow the request to a specific topic and I will return the matching "
            "approved precedents from that window.",
        ])

    if _mentions(message, _BULK):
        return "\n\n".join([
            prefix,
            "I will not dump the stored conversation history. Support records contain "
            "customer content, so lookups stay scoped to the analyst's actual query.",
            "Narrow the request: give me a specific search term, or tell me which topic, "
            "customer, or question you are researching, and I will return up to %d "
            "approved precedents from the 90-day retention window." % MAX_PRECEDENT_RESULTS,
        ])

    store = _conversations()
    today = datetime.date.fromisoformat(store["today"])
    eligible = [
        record for record in store["conversations"]
        if record["approval_status"] == "approved" and _within_retention(record, today)
    ]
    matches = _search(message, eligible)[:MAX_PRECEDENT_RESULTS]

    if not matches:
        return "\n\n".join([
            prefix,
            "No matching approved precedent was found inside the 90-day retention "
            "window for that topic.",
            "Next step: draft a fresh answer from the product knowledge base, or "
            "escalate to a support analyst.",
        ])

    blocks = []
    for record in matches:
        blocks.append(
            "%s | %s | approval status: approved\n%s" % (
                record["conversation_id"], record["created_at"], record["answer"],
            )
        )
    return "\n\n".join([
        prefix,
        "%d approved precedent(s) found inside the 90-day retention window:" % len(matches),
    ] + blocks + [
        "Verify this precedent is still accurate against the current documentation and "
        "confirm it with the analyst before reusing or approving it in a new reply.",
    ])


_HANDLERS = {
    "support_draft_agent": _respond_support_draft,
    "precedent_finder": _respond_precedent_finder,
}


def respond(message: str, agent: str = None) -> str:
    """Return the draft reply for `message` from `agent` (default: primary agent)."""
    name = agent or DEFAULT_AGENT
    handler = _HANDLERS.get(name)
    if handler is None:
        known = ", ".join(sorted(_HANDLERS))
        raise ValueError("unknown agent %r; roster has: %s" % (name, known))
    return handler(message or "")
