"""Support Copilot — generated by the harness agentic-app scaffold.

Composition contract: db (persistence-core), agent_runtime (agent-runtime),
models.TABLES (generated from the approved data model).
"""
import uuid
from datetime import datetime, timezone

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

from agent_runtime import corpus_info, mode, respond_with_citations
from db import store
from models import TABLES

app = FastAPI(title="Support Copilot")


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


class ChatRequest(BaseModel):
    message: str
    conversation_id: str | None = None


@app.get("/health")
def health():
    return {"status": "ok"}


@app.get("/agent/mode")
def agent_mode():
    return mode()


@app.get("/agents")
def agents():
    """The app's configured agent roster — roles, tools, guardrails, evals.

    Transparency contract: users can always see which agents an app runs.
    """
    import json
    import os

    roster_path = os.path.join(os.path.dirname(__file__), "..", "agents", "roster.json")
    with open(roster_path, encoding="utf-8") as f:
        return json.load(f)


@app.get("/corpus")
def corpus():
    """The product-knowledge corpus loaded from the local documents folder at
    startup (REQ-017) — visible so an analyst can see what the assistant is
    grounded in before trusting a draft."""
    return corpus_info()


def _find_conversation(conversation_id: str) -> dict | None:
    for row in store.list("conversations"):
        if row.get("conversation_id") == conversation_id:
            return row
    return None


def _ensure_conversation(conversation_id: str, subject: str) -> dict:
    """A client-supplied conversation_id is stable: reuse the row if it already exists."""
    existing = _find_conversation(conversation_id)
    if existing:
        return existing
    now = _now()
    return store.insert(
        "conversations",
        {"conversation_id": conversation_id, "created_at": now, "updated_at": now, "subject": subject[:120]},
    )


@app.post("/chat")
def chat(req: ChatRequest):
    # conversation_id is optional (REQ-002): a bare {"message": ...} still works
    # and still returns "reply" — the base test suite and compose smoke keep passing.
    conversation_id = req.conversation_id or f"conv-{uuid.uuid4().hex[:12]}"
    _ensure_conversation(conversation_id, req.message)
    sequence = sum(1 for m in store.list("messages") if m.get("conversation_id") == conversation_id) + 1

    # Retrieval before generation (REQ-003): the reply is composed only from
    # what the corpus search found, and the same search backs the citations
    # shown to the analyst and filed with the conversation record (REQ-011).
    reply, sources = respond_with_citations(req.message)

    message = store.insert(
        "messages",
        {
            "conversation_id": conversation_id,
            "sequence": sequence,
            "role": "assistant",
            "analyst_question": req.message,
            "assistant_draft": reply,
            "created_at": _now(),
        },
    )
    citations = [
        store.insert(
            "citations",
            {
                "message_id": message["id"],
                "source_title": source["title"],
                "source_passage": source["passage"],
                "source_url": source.get("url", ""),
            },
        )
        for source in sources
    ]
    return {"reply": reply, "conversation_id": conversation_id, "message_id": message["id"], "citations": citations}


@app.get("/api/{table}")
def list_rows(table: str):
    if table not in TABLES:
        raise HTTPException(status_code=404, detail="unknown table")
    return store.list(table)


@app.post("/api/{table}")
def create_row(table: str, row: dict):
    if table not in TABLES:
        raise HTTPException(status_code=404, detail="unknown table")
    return store.insert(table, row)
