"""Underwriting Command Center — generated by the harness agentic-app scaffold.

Composition contract: db (persistence-core), agent_runtime (agent-runtime),
models.TABLES (generated from the approved data model).
"""
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

from agent_runtime import mode, respond
from db import store
from models import TABLES

app = FastAPI(title="Underwriting Command Center")

# Composed module extensions: any backend/ext_*.py exposing `router` mounts
# automatically. This is how capability modules add API surface without ever
# editing this file — the module system's extension point.
import glob as _glob  # noqa: E402
import importlib as _importlib  # noqa: E402
import os as _os  # noqa: E402

for _ext in sorted(_glob.glob(_os.path.join(_os.path.dirname(__file__), "ext_*.py"))):
    _mod = _importlib.import_module(_os.path.basename(_ext)[:-3])
    if hasattr(_mod, "router"):
        app.include_router(_mod.router)
    if hasattr(_mod, "install"):
        _mod.install(app)


class ChatRequest(BaseModel):
    message: str


@app.get("/health")
def health():
    return {"status": "ok"}


@app.get("/agent/mode")
def agent_mode():
    return mode()


@app.get("/agents")
def agents():
    """The app's configured agent roster — roles, tools, guardrails, evals.

    Transparency contract: users can always see which agents an app runs.
    """
    import json
    import os

    roster_path = os.path.join(os.path.dirname(__file__), "..", "agents", "roster.json")
    with open(roster_path, encoding="utf-8") as f:
        return json.load(f)


@app.post("/chat")
def chat(req: ChatRequest):
    return {"reply": respond(req.message)}


# Rows carrying the deal of record, its human gates, its money or its
# append-only trail are writable ONLY through their guarded endpoints
# (/deals, /deals/{ref}/triage, /deals/{ref}/drafts/{type}/review), which
# resolve a named identity, check the role grant, derive tier and exposure in
# deterministic Python and append an audit row. The generic table API is a
# scaffold convenience and must never become a path around those controls.
GUARDED_TABLES = {
    "deals",
    "documents",
    "document_locations",
    "agent_runs",
    "agent_drafts",
    "approvals",
    "declines",
    "stage_transitions",
    "audit_log",
    "users",
    "analyst_queues",
    "policy_exceptions",
    "risk_grades",
    "ratios",
    # slice 2: the accepted spread and its citation trail are deal-of-record
    # money data — written only by the draft-review gate that promotes them.
    "spread_line_items",
    "citations",
}

# Columns never returned over a generic read.
SECRET_COLUMNS = {"password_hash"}


@app.get("/api/{table}")
def list_rows(table: str):
    if table not in TABLES:
        raise HTTPException(status_code=404, detail="unknown table")
    return [{k: v for k, v in row.items() if k not in SECRET_COLUMNS} for row in store.list(table)]


@app.post("/api/{table}")
def create_row(table: str, row: dict):
    if table not in TABLES:
        raise HTTPException(status_code=404, detail="unknown table")
    if table in GUARDED_TABLES:
        raise HTTPException(
            status_code=403,
            detail=f"'{table}' rows are written only through their guarded endpoints",
        )
    return store.insert(table, row)
