"""Support Copilot — generated by the harness agentic-app scaffold.

Composition contract: db (persistence-core), agent_runtime (agent-runtime),
models.TABLES (generated from the approved data model).
"""
import uuid
from datetime import datetime, timezone

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

from agent_runtime import mode, respond
from db import store
from models import TABLES

app = FastAPI(title="Support Copilot")

# Seeded local analyst accounts (v0, no external auth module in this compose):
# ?token=<token> -> analyst_id. REQ-021/REQ-015: every history read requires one.
ANALYST_TOKENS = {"analyst1": "analyst-1"}

SIGN_IN_MESSAGE = "Please sign in with a valid local analyst account to view conversation history."


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _require_analyst(token: str | None) -> str:
    """Resolve the seeded local-account token to an analyst_id, else 401 (REQ-015, REQ-021)."""
    analyst_id = ANALYST_TOKENS.get(token) if token else None
    if not analyst_id:
        raise HTTPException(status_code=401, detail=SIGN_IN_MESSAGE)
    return analyst_id


def _find_conversation(conversation_id: str) -> dict | None:
    for row in store.list("conversations"):
        if row.get("conversation_id") == conversation_id:
            return row
    return None


def _ensure_conversation(conversation_id: str, analyst_id: str | None, topic: str) -> dict:
    """A client-supplied conversation_id is stable: reuse the row if it already exists."""
    existing = _find_conversation(conversation_id)
    if existing:
        return existing
    return store.insert(
        "conversations",
        {
            "conversation_id": conversation_id,
            "analyst_id": analyst_id,
            "topic": topic[:120],
            "created_at": _now(),
            "updated_at": _now(),
        },
    )


class ChatRequest(BaseModel):
    message: str
    conversation_id: str | None = None
    analyst_id: str | None = None


@app.get("/health")
def health():
    return {"status": "ok"}


@app.get("/agent/mode")
def agent_mode():
    return mode()


@app.post("/chat")
def chat(req: ChatRequest):
    # conversation_id is optional (REQ-003/REQ-006): a bare {"message": ...} still works
    # and still returns "reply" — the base test suite and compose smoke keep passing.
    conversation_id = req.conversation_id or f"conv-{uuid.uuid4().hex[:12]}"
    _ensure_conversation(conversation_id, req.analyst_id, req.message)
    store.insert(
        "messages",
        {"conversation_id": conversation_id, "role": "user", "content": req.message, "created_at": _now()},
    )
    reply = respond(req.message)
    store.insert(
        "messages",
        {"conversation_id": conversation_id, "role": "assistant", "content": reply, "created_at": _now()},
    )
    return {"reply": reply, "conversation_id": conversation_id}


# History reads live outside /api/ so the /api/{table} catch-all below never
# shadows them, and both require the seeded local analyst session (REQ-015).
@app.get("/conversations")
def list_conversations(token: str | None = None):
    _require_analyst(token)
    return {"conversations": store.list("conversations")}


@app.get("/conversations/{conversation_id}")
def get_conversation(conversation_id: str, token: str | None = None):
    _require_analyst(token)
    conversation = _find_conversation(conversation_id)
    if conversation is None:
        raise HTTPException(status_code=404, detail="unknown conversation")
    messages = [m for m in store.list("messages") if m.get("conversation_id") == conversation_id]
    return {"conversation": conversation, "messages": messages}


@app.get("/api/{table}")
def list_rows(table: str):
    if table not in TABLES:
        raise HTTPException(status_code=404, detail="unknown table")
    return store.list(table)


@app.post("/api/{table}")
def create_row(table: str, row: dict):
    if table not in TABLES:
        raise HTTPException(status_code=404, detail="unknown table")
    return store.insert(table, row)
