"""Support Copilot — generated by the harness agentic-app scaffold.

Composition contract: db (persistence-core), agent_runtime (agent-runtime),
models.TABLES (generated from the approved data model).
"""
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

from agent_runtime import mode, respond
from db import store
from models import TABLES

app = FastAPI(title="Support Copilot")


class ChatRequest(BaseModel):
    message: str


@app.get("/health")
def health():
    return {"status": "ok"}


@app.get("/agent/mode")
def agent_mode():
    return mode()


@app.get("/agents")
def agents():
    """The app's configured agent roster — roles, tools, guardrails, evals.

    Transparency contract: users can always see which agents an app runs.
    """
    import json
    import os

    roster_path = os.path.join(os.path.dirname(__file__), "..", "agents", "roster.json")
    with open(roster_path, encoding="utf-8") as f:
        return json.load(f)


@app.post("/chat")
def chat(req: ChatRequest):
    return {"reply": respond(req.message)}


@app.get("/api/{table}")
def list_rows(table: str):
    if table not in TABLES:
        raise HTTPException(status_code=404, detail="unknown table")
    return store.list(table)


@app.post("/api/{table}")
def create_row(table: str, row: dict):
    if table not in TABLES:
        raise HTTPException(status_code=404, detail="unknown table")
    return store.insert(table, row)
