"""Underwriting Command Center — generated by the harness agentic-app scaffold.

Composition contract: db (persistence-core), agent_runtime (agent-runtime),
models.TABLES (generated from the approved data model).
"""
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

from agent_runtime import mode, respond
from db import store
from models import TABLES

app = FastAPI(title="Underwriting Command Center")

# Composed module extensions: any backend/ext_*.py exposing `router` mounts
# automatically. This is how capability modules add API surface without ever
# editing this file — the module system's extension point.
#
# ORDERING CONTRACT: this loop runs BEFORE the generic /api/{table} catch-all
# at the bottom of this file is declared, so every ext router — the feature
# endpoints (/api/deals, /api/pipeline, …) and the workflow-run routes in
# ext_workflow_runs.py (/workflows, /workflows/{name}/start,
# /workflows/runs/{id}/tick, /workflows/runs/{id}) — is matched first and can
# never be shadowed. `_assert_route_ordering()` at the end of this file
# enforces that for anything added later.
import glob as _glob  # noqa: E402
import importlib as _importlib  # noqa: E402
import os as _os  # noqa: E402

for _ext in sorted(_glob.glob(_os.path.join(_os.path.dirname(__file__), "ext_*.py"))):
    _mod = _importlib.import_module(_os.path.basename(_ext)[:-3])
    if hasattr(_mod, "router"):
        app.include_router(_mod.router)
    if hasattr(_mod, "install"):
        _mod.install(app)


# An unbounded prompt is a denial-of-service and a prompt-injection surface, so
# the chat message is length-bounded at the edge: anything outside the bound is
# a 422 from FastAPI's validation before it ever reaches the model.
MAX_CHAT_MESSAGE_CHARS = 4000


class ChatRequest(BaseModel):
    message: str = Field(min_length=1, max_length=MAX_CHAT_MESSAGE_CHARS)


@app.get("/health")
def health():
    return {"status": "ok"}


@app.get("/agent/mode")
def agent_mode():
    return mode()


@app.get("/agents")
def agents():
    """The app's configured agent roster — roles, tools, guardrails, evals.

    Transparency contract: users can always see which agents an app runs.
    """
    import json
    import os

    roster_path = os.path.join(os.path.dirname(__file__), "..", "agents", "roster.json")
    with open(roster_path, encoding="utf-8") as f:
        return json.load(f)


@app.post("/chat")
def chat(req: ChatRequest):
    return {"reply": respond(req.message)}


# ---------------------------------------------------------------------------
# Generic /api/{table} passthrough — READ ONLY, and only for the reference
# tables the UI actually reads.
#
# Security posture (governance code_audit finding, fixed here):
#   * Generic WRITE access is GONE. There is no store.insert() reachable from
#     this file. Every mutation in this app goes through an explicit endpoint
#     in an ext_*.py that resolves the caller with
#     identity.require_actor(...) and writes an audit row.
#   * Generic READ is restricted to GENERIC_READ_TABLES below — the
#     non-sensitive reference/lookup data the frontend reads directly
#     (decline reason codes for the adverse-action dropdown, the active
#     lending policy rules, and the business-day calendar behind SLA ageing).
#     Deal records, spreads, ratios, grades, memos, exceptions, approvals,
#     agent outputs, human reviews, Q&A sessions, the audit log and the users
#     table are NOT readable here: they carry borrower data, decisions, or
#     PII and are served only by access-controlled feature endpoints.
#
# These routes are declared LAST on purpose: /api/{table} is a catch-all and
# would shadow any /api/... route registered after it.
# ---------------------------------------------------------------------------
GENERIC_READ_TABLES = {
    "lending_policy",
    "adverse_action_reasons",
    "business_calendar",
}

_WRITE_METHODS = ["POST", "PUT", "PATCH", "DELETE"]


@app.get("/api/{table}")
def list_rows(table: str):
    if table not in TABLES:
        raise HTTPException(status_code=404, detail="unknown table")
    if table not in GENERIC_READ_TABLES:
        raise HTTPException(
            status_code=403,
            detail=(
                f"table '{table}' is not readable through the generic table API; "
                "use the feature endpoint for it, which enforces access control"
            ),
        )
    return store.list(table)


@app.api_route("/api/{table}", methods=_WRITE_METHODS, include_in_schema=False)
def generic_write_disabled(table: str):
    """Generic table writes are permanently disabled — see the note above."""
    raise HTTPException(
        status_code=405,
        detail=(
            "the generic table API is read-only; mutations must go through an "
            "explicit endpoint that enforces role authority and records an audit entry"
        ),
    )


def _assert_route_ordering():
    """Fail fast if a later slice registers an /api/... route that this
    catch-all would swallow. Import-time guard, so a shadowed endpoint is a
    boot error rather than a silent 404/403 in production."""
    paths = [getattr(r, "path", "") for r in app.routes]
    catchall = paths.index("/api/{table}")
    shadowed = [
        p
        for p in paths[catchall + 1:]
        if p.startswith("/api/") and p != "/api/{table}"
    ]
    if shadowed:
        raise RuntimeError(
            "these routes are registered after the /api/{table} catch-all and "
            f"would be shadowed: {shadowed}"
        )


_assert_route_ordering()
