"""Support Copilot — generated by the harness agentic-app scaffold.

Composition contract: db (persistence-core), agent_runtime (agent-runtime),
models.TABLES (generated from the approved data model).
"""
import re
import uuid
from datetime import datetime, timezone

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

from agent_runtime import mode, respond
from db import store
from models import TABLES

app = FastAPI(title="Support Copilot")

# Seeded local analyst accounts (v0, no external auth module in this compose):
# ?token=<token> -> analyst_id. REQ-021/REQ-015: every history read requires one.
ANALYST_TOKENS = {"analyst1": "analyst-1"}

SIGN_IN_MESSAGE = "Please sign in with a valid local analyst account to view conversation history."

# REQ-023: delivery is always a manual copy by the analyst — the agent holds no send tool.
DELIVERY_REMINDER = (
    "Remember: delivery is a manual copy of the approved text into the existing ticketing tool — "
    "the agent holds no send tool."
)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _extract_sources(reply: str) -> list[str]:
    """Pull the doc- ids the agent cited (after the 'Sources:' line) out of a reply."""
    return re.findall(r"doc-[A-Za-z0-9_-]+", reply)


def _require_analyst(token: str | None) -> str:
    """Resolve the seeded local-account token to an analyst_id, else 401 (REQ-015, REQ-021)."""
    analyst_id = ANALYST_TOKENS.get(token) if token else None
    if not analyst_id:
        raise HTTPException(status_code=401, detail=SIGN_IN_MESSAGE)
    return analyst_id


def _find_conversation(conversation_id: str) -> dict | None:
    for row in store.list("conversations"):
        if row.get("conversation_id") == conversation_id:
            return row
    return None


def _latest_draft(conversation_id: str) -> dict | None:
    matches = [d for d in store.list("drafts") if d.get("conversation_id") == conversation_id]
    return matches[-1] if matches else None


def _with_latest_draft_state(conversation: dict) -> dict:
    """Read-time enrichment (never persisted): expose the conversation's latest
    draft approval_state so the History screen can display/filter on it (REQ-009)
    without duplicating drafts data into the conversations table."""
    draft = _latest_draft(conversation.get("conversation_id"))
    enriched = dict(conversation)
    enriched["approval_state"] = draft["approval_state"] if draft else None
    return enriched


def _conversation_search_text(conversation_id: str, topic: str | None) -> str:
    """Searchable text for one conversation: topic plus every message and draft body.
    Retention is indefinite (REQ-022), so this always searches the full stored history,
    never a rolling window."""
    parts = [topic or ""]
    parts.extend(
        m.get("content") or "" for m in store.list("messages") if m.get("conversation_id") == conversation_id
    )
    parts.extend(
        d.get("content") or "" for d in store.list("drafts") if d.get("conversation_id") == conversation_id
    )
    return " ".join(parts).lower()


def _matches_query(conversation: dict, terms: list[str]) -> bool:
    haystack = _conversation_search_text(conversation.get("conversation_id"), conversation.get("topic"))
    return all(term in haystack for term in terms)


def _ensure_conversation(conversation_id: str, analyst_id: str | None, topic: str) -> dict:
    """A client-supplied conversation_id is stable: reuse the row if it already exists."""
    existing = _find_conversation(conversation_id)
    if existing:
        return existing
    return store.insert(
        "conversations",
        {
            "conversation_id": conversation_id,
            "analyst_id": analyst_id,
            "topic": topic[:120],
            "created_at": _now(),
            "updated_at": _now(),
        },
    )


class ChatRequest(BaseModel):
    message: str
    conversation_id: str | None = None
    analyst_id: str | None = None


class ApprovalRequest(BaseModel):
    conversation_id: str
    decision: str  # "approve" | "reject"
    analyst_id: str | None = None
    content: str | None = None
    token: str | None = None


class PrecedentSearchRequest(BaseModel):
    q: str
    token: str | None = None


class DraftReuseRequest(BaseModel):
    conversation_id: str
    source_conversation_id: str
    analyst_id: str | None = None
    token: str | None = None


def _latest_approved_draft(conversation_id: str) -> dict | None:
    matches = [
        d
        for d in store.list("drafts")
        if d.get("conversation_id") == conversation_id and d.get("approval_state") == "approved"
    ]
    return matches[-1] if matches else None


# precedent_finder (agents/roster.json's second agent) is analyst-gated, approved-only,
# and holds no send/approve tool (REQ-014/REQ-015/REQ-023) — see agent_runtime's
# precedent-branch docstring for why this endpoint queries db.store directly rather
# than routing through agent_runtime.respond().
PRECEDENT_VERIFY_NOTE = "Please verify it is still accurate before reusing this answer."
PRECEDENT_ONLY_APPROVED_NOTE = f"Only approved conversations are ever surfaced as precedent — {PRECEDENT_VERIFY_NOTE}"
PRECEDENT_MAX_RESULTS = 5


@app.get("/health")
def health():
    return {"status": "ok"}


@app.get("/agent/mode")
def agent_mode():
    return mode()


@app.post("/chat")
def chat(req: ChatRequest):
    # conversation_id is optional (REQ-003/REQ-006): a bare {"message": ...} still works
    # and still returns "reply" — the base test suite and compose smoke keep passing.
    conversation_id = req.conversation_id or f"conv-{uuid.uuid4().hex[:12]}"
    _ensure_conversation(conversation_id, req.analyst_id, req.message)
    store.insert(
        "messages",
        {"conversation_id": conversation_id, "role": "user", "content": req.message, "created_at": _now()},
    )
    reply = respond(req.message)
    assistant_message = store.insert(
        "messages",
        {"conversation_id": conversation_id, "role": "assistant", "content": reply, "created_at": _now()},
    )
    # Every assistant reply is a draft, never a delivered answer (REQ-007/REQ-011/REQ-023):
    # it starts "pending" and only an authenticated analyst's POST /approvals can change that.
    draft = store.insert(
        "drafts",
        {
            "message_id": assistant_message["id"],
            "conversation_id": conversation_id,
            "content": reply,
            "sources": _extract_sources(reply),
            "approval_state": "pending",
            "approved_by": None,
            "approved_at": None,
            "created_at": _now(),
        },
    )
    return {"reply": reply, "conversation_id": conversation_id, "draft": draft}


# History reads live outside /api/ so the /api/{table} catch-all below never
# shadows them, and both require the seeded local analyst session (REQ-015).
@app.get("/conversations")
def list_conversations(token: str | None = None, q: str | None = None, state: str | None = None):
    # q: keyword search across the full retained history (topic + message + draft
    # content, REQ-004/REQ-022). state: filter on the conversation's latest draft
    # approval_state (REQ-009). Both are optional and gated by the same analyst
    # session as every other history read.
    _require_analyst(token)
    rows = [_with_latest_draft_state(row) for row in store.list("conversations")]
    if q:
        terms = [t for t in q.lower().split() if t]
        if terms:
            rows = [row for row in rows if _matches_query(row, terms)]
    if state:
        rows = [row for row in rows if row.get("approval_state") == state]
    if (q or state) and not rows:
        return {
            "conversations": [],
            "message": "No matching prior conversation found for this search.",
        }
    return {"conversations": rows}


@app.get("/conversations/{conversation_id}")
def get_conversation(conversation_id: str, token: str | None = None):
    _require_analyst(token)
    conversation = _find_conversation(conversation_id)
    if conversation is None:
        raise HTTPException(status_code=404, detail="unknown conversation")
    messages = [m for m in store.list("messages") if m.get("conversation_id") == conversation_id]
    return {"conversation": conversation, "messages": messages}


# Draft reads and the approval gate also live outside /api/ (same reason as history above)
# and require the same seeded local analyst session (REQ-015). Approval is analyst-only:
# there is no agent tool anywhere in this app that can set approval_state itself.
@app.get("/drafts")
def list_drafts(conversation_id: str, token: str | None = None):
    _require_analyst(token)
    rows = [d for d in store.list("drafts") if d.get("conversation_id") == conversation_id]
    return {"drafts": rows}


@app.post("/approvals")
def create_approval(req: ApprovalRequest, token: str | None = None):
    # The token is the source of truth for identity — accept it from the body (as the
    # acceptance flow does) or a query param, same as every other analyst-gated endpoint.
    analyst_id = _require_analyst(req.token or token)
    if req.decision not in ("approve", "reject"):
        raise HTTPException(status_code=400, detail="decision must be 'approve' or 'reject'")
    draft = _latest_draft(req.conversation_id)
    if draft is None:
        raise HTTPException(status_code=404, detail="no draft found for this conversation")
    changes = {
        "approval_state": "approved" if req.decision == "approve" else "rejected",
        "approved_by": analyst_id,
        "approved_at": _now(),
    }
    if req.decision == "approve" and req.content:
        # An analyst may edit the draft text before approving; that edited text becomes
        # the record of what was approved (REQ-010).
        changes["content"] = req.content
    updated = store.update("drafts", draft["id"], **changes)
    message = f"Draft {updated['approval_state']} by {analyst_id} at {updated['approved_at']}. {DELIVERY_REMINDER}"
    return {"draft": updated, "message": message}


# Precedent lookup and reuse (REQ-004/REQ-014/REQ-015/REQ-018) also live outside /api/
# so the /api/{table} catch-all never shadows them, and require the same seeded local
# analyst session as every other history/draft read.
@app.post("/precedents/search")
def search_precedents(req: PrecedentSearchRequest, token: str | None = None):
    _require_analyst(req.token or token)
    terms = [t for t in req.q.lower().split() if t]
    approved = [d for d in store.list("drafts") if d.get("approval_state") == "approved"]
    matches = []
    for draft in approved:
        conversation = _find_conversation(draft.get("conversation_id")) or {}
        haystack = " ".join(
            [
                draft.get("content") or "",
                conversation.get("topic") or "",
                " ".join(draft.get("sources") or []),
            ]
        ).lower()
        if not terms or all(term in haystack for term in terms):
            matches.append(draft)
    if not matches:
        return {"precedents": [], "message": "No matching prior conversation found for this search."}
    precedents = [
        {
            "conversation_id": d["conversation_id"],
            "content": d["content"],
            "sources": d.get("sources", []),
            "approval_state": d.get("approval_state"),
            "approved_by": d.get("approved_by"),
            "approved_at": d.get("approved_at"),
        }
        for d in matches[:PRECEDENT_MAX_RESULTS]
    ]
    return {"precedents": precedents, "message": PRECEDENT_ONLY_APPROVED_NOTE}


@app.post("/drafts/reuse")
def reuse_draft(req: DraftReuseRequest, token: str | None = None):
    analyst_id = _require_analyst(req.token or token)
    source = _latest_approved_draft(req.source_conversation_id)
    if source is None:
        raise HTTPException(status_code=404, detail="no approved draft found for that conversation")
    # The target conversation is expected to already exist (created by an earlier
    # POST /chat turn); _ensure_conversation only creates it if it truly doesn't.
    _ensure_conversation(req.conversation_id, req.analyst_id or analyst_id, source["content"])
    note = (
        f"Reused precedent from {req.source_conversation_id} (approved by {source.get('approved_by')} at "
        f"{source.get('approved_at')}). {PRECEDENT_VERIFY_NOTE} This draft is pending your approval like any other."
    )
    assistant_message = store.insert(
        "messages",
        {"conversation_id": req.conversation_id, "role": "assistant", "content": note, "created_at": _now()},
    )
    # A reused precedent is still just a draft — never auto-approved — and it always
    # records where it came from (source_conversation_id) so provenance is never lost.
    draft = store.insert(
        "drafts",
        {
            "message_id": assistant_message["id"],
            "conversation_id": req.conversation_id,
            "content": source["content"],
            "sources": source.get("sources", []),
            "approval_state": "pending",
            "approved_by": None,
            "approved_at": None,
            "source_conversation_id": req.source_conversation_id,
            "created_at": _now(),
        },
    )
    return {"draft": draft, "message": note}


@app.get("/api/{table}")
def list_rows(table: str):
    if table not in TABLES:
        raise HTTPException(status_code=404, detail="unknown table")
    return store.list(table)


@app.post("/api/{table}")
def create_row(table: str, row: dict):
    if table not in TABLES:
        raise HTTPException(status_code=404, detail="unknown table")
    return store.insert(table, row)
